title: Uri Sh.
subtitle: Making and Engineering
logo: logo.png
author:
  name: Uri Shani
  copyright-year: 2020
  email: urish@urishx.com
description: > # this means to ignore newlines until "show_excerpts:"
  A portfolio centered site with a blog, to feature my adventures and projects in 
  making, programming, and engineering. Built in Jekyll, to be served from Github pages.
banner: banner.png
# baseurl: '/Jekyll-portfolio' # the subpath of your site, e.g. /blog
url: 'https://urishx.github.io' # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true # set to true to show excerpts on the homepage

timezone: IL

collections:
  portfolio:
    sort_by: place
    order:
      - perpetuum-mobile.md
      - niti-light.md
      - uav-fuel-tank.md
      - toy-sound-box-prototype.md
      - mechanical-sieve.md
      - fuel-gun.md
      - smart-scale.md
      - concrete-pot.md
      - elastomeric-part-design.md
      - aerial-warning-ball.md
      - ziv-foot-rest.md
      - parametric-design-openscad.md
      - web-ble-basic-control.md
      - ab4mc.md
      - cap-sense-name-card.md
      - sus-comp-agriwaste.md

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: '%b %-d, %Y'
  skin: solarized

  # generate social links in footer
  social_links:
    hackaday: UriSh
    twitter: UriShX
    github: UriShX
    # devto: jekyll
    # dribbble: jekyll
    facebook: uri.sh.982
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: urishx
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-highlight-param
  - jekyll-remote-include
