# This CI will run after publish a new release

name: Push to Other Repo and Make a PR

on:
  # release:
  #   types: [published]
  push:
    branches:
      - master
      # It is highly recommended that you only run this action on push to a
      # specific branch, eg. master or source (if on *.github.io repo)
  
jobs:
  processing_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push then create PR
        uses: sepulsa/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}

            DEST_GITHUB_USERNAME: 'urishx'
            DEST_REPO_NAME: 'microblog'
            USER_EMAIL: 'usdogi@gmail.com'
            PUSH_TO_BRANCH: 'jekyll-portfolio'
            PR_TO_BRANCH: 'master'
            # You can add multiple source file or folder separate by space
            SRC_DIR: '_includes _layouts _sass assets/script' 
            # You can create nested folder
            # DEST_DIR: 'initiative/system_name'
            # You can rename with format source(comma)target
            # Multiple line if you want to move multiple file / folder
            # RENAME: >-
            #         readme.adoc,docs.adoc
            #         docs,docs
            # Add your custom Pull Request message
            PR_MESSAGE: 'Edits in github.com/urishx/jekyll-portfoilio'
